### ISSUE TITLE
Instrumenter goes crazy with UMD format and ecmascript on node

### ISSUE THREAD

**Issue by Kflash** [istanbuljs/istanbul-lib-instrument#7]
Hey! I spent some time now with latest Alpha release, and I'm impressed! Great work!
However. I found a few strange things...

In the project I tried this I'm using TypeScript. First I figured out is that Ecmascript - ES6 - isn't working with this Istanbul release? 

I know import & export statements isn't working in the node.js environment, and a possible workaround is to use sourcemap.  But still "normal" ES6 syntax that Node v.6.x are accepting was throwing at me.
How to solve this? Sourcemap?

The most crazy thing I discovered was the UMD format.

With "normal" TS transpile without modules give me 100% correct coverage.
If I transpile down to ES5 with UMD as module, the instrumenter goes crazy!
The coverage result ending up to be 46% even if all lines are covered!!

The reported uncovered lines is also wrong if you do this. The .js file is only on 1 line, but get reported back that both line 6 and 7 are not covered!!

Functions are reported to be 2, but there are no functions.

So you better understand...

`tsc --outDir ./build/es5 -t es5 -m umd`

Transpile down from TS to ES5, and run coverage on the transpiled files.

If I do it like this 

`tsc --outDir ./build/es5 -t es5`

coverage is back to 100% and instrumenter works perfect! EXCEPT if I add some more code to the main file, then the instrumenter reports wrong line number!

With TypeScript v. 2.0, dead code elimination for ES modules. Meaning you can set taget to ES5 and module to ES6.

The instrumenter doesn't seem to like that either? Is that something to be supported in a future release? Or I'm forced to transpile down to ES5 or use SourceMap?

This can be reproduced easy. 
https://github.com/jeibo/workflow/blob/master/scripts/coveralls.sh#L27-L30

If you run this script, and change line 27.

And look at this file: https://github.com/jeibo/workflow/blob/master/src/jeibo.ts

If you run coverage on it, I get reported that line 7 isn't covered. In fact line 3, 4, 5 is the lines who isn't covered! Or line 5, 6, 7 in the transpiled code.

Coverage decreased (-33.3%) to 66.667%

**Comment by gotwarlost** [comment]
Thanks for the detailed feedback - just the thing I was looking for v1.1.

Give me some time to look into it. The ES6 thing is really bizarre because the instrumenter has ES6 unit tests and they all work. I'll see what is going on by cloning your repo.

**Comment by Kflash** [comment]
Hey. Thanks for quick reply!  Sure no problem. And If I find more strange things I will let youknow.

For now I just discovered another funny thing.

Look at this: https://github.com/jeibo/workflow/blob/master/test/client/jeibo.ts#L19-L21

And if you look into the source code: https://github.com/jeibo/workflow/blob/master/src/jeibo.ts#L7

You see that line 7, and 8 are covered, right?

The instrumenter reports now that the uncovered lines is 7, and 8 !!!

**Comment by gotwarlost** [comment]
Believe it or not, things are actually working mostly as expected (when I fixed a couple of things in your script). The two things wrong in your script are:

1. `--harmony` is not in effect because `_mocha` has no way of turning this on. This is why you see spurious es6 errors.

2. you are not compiling the TS with the `--sourceMap` option so what is getting instrumented _and_ reported on in the ES5 code without any source map processing. This explains the unexpected functions and such.

So do this in your coveralls script:

The test command should be:

```
node --harmony ./node_modules/istanbul/lib/cli.js cover --root build/es5/src \
     ./node_modules/mocha/bin/_mocha -- -R spec ./build/es5/test/**/*.js
```

the TSC compile command should include `--sourceMap`. _All_ of the below versions of that command produce identical coverage output.

```
./node_modules/.bin/tsc --sourceMap --outDir ./build/es5 -t es2015 -m commonjs
./node_modules/.bin/tsc --sourceMap --outDir ./build/es5 -t es5
./node_modules/.bin/tsc --sourceMap --outDir ./build/es5 -t es5 -m umd
```

The one thing that is messed up is that the HTML report is showing coverage for lines offset by 1, instead of the correct lines. This may be related to source maps and I need to dig deeper into why this is happening.

Lines 4 and 5 should be red and 7 should be green (instead of 5-6, 8).

![cov](https://cloud.githubusercontent.com/assets/1056819/16355635/97819860-3ada-11e6-9244-227111ffe7d2.png)

**Comment by Kflash** [comment]
I got it almost working. Regarding TypeScript 2.0. Look at this link: https://github.com/Microsoft/TypeScript/issues/6319 

So if I change the build to this: `./node_modules/.bin/tsc --sourceMap --outDir ./build/es5 -t es5 -m es6`
it  throws.

**Comment by gotwarlost** [comment]
I believe that is an invalid combination since node.js doesn't support es6 modules. It should be node throwing in this case.

**Comment by gotwarlost** [comment]
If you look at the typescript issue, that combination is for things like webpack that do additional processing before delivering the code to the browser. That use case is not one for node as far as I can tell.

**Comment by Kflash** [comment]
ES modules is going to be supported. But because Node's feature support is tied to V8 I agree this can't be legal until ES6 is fully supported in V8.  You'll need to  use either Babel or avoid unsupported features.  
In this case I'm using ts-node that should handle such things with the --require arg.

Anyway. Did you figure out what's wrong with the HTML report?

**Comment by Kflash** [comment]
Not sure if this is related, but the numbers on the generated report are pushed out of order sometimes
```
42 - 13	23 - 10	16 + 4	7 - 14	1.0 - 1.0
70.  23	10	7	3	1.0 - 1.0
73.33	53	30	22	8	1.0 - 1.0
85.0	49	20 - 1	17 - 1	3	1.0 - 1.0
`````````

**Comment by gotwarlost** [comment]
This was extremely painful to find. The root cause was that "something" was inserting a `"use strict";` statement at the top of the JS file by the time istanbul saw it which meant that the source mapping was basically wrong.

So, transpiled file looks like:
```
"use strict";
some code;
```

and what istanbul sees is:

```
"use strict";
"use strict";
some code
```

That something turned out to be the "buble compiler" installed via your `mocha.opts` file. Once I removed it from `mocha.opts` it all works.

When you report bugs please keep external dependencies, magic files and magic environment variables to a minimum. This was extremely painful to debug.

**Comment by gotwarlost** [comment]
![cov2](https://cloud.githubusercontent.com/assets/1056819/16357555/914c34e0-3b17-11e6-83e7-66893a414195.png)

**Comment by Kflash** [comment]
Hey. I see it's working perfect now. Sorry for the painfull bug hunt. I addressed the issue to where I think it belong. Great job with Istanbul :+1:
